env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2020 # Включает поддержку конструкции import.meta.url
  sourceType: module
rules: {
  no-console: off,
  import/extensions: 0,
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для 4 констант
}


